### ISSUE TITLE
V8 optimizer disabled on _hasown

### ISSUE THREAD

**Issue by niklaskarla** [traviskaufman/cycloneJS#30]
I fiddled around with the performance of this library since I found it being significantly slower than a straight 'for (var prop in orig)' implementation. I found that replacing the below line in _handleCollectionClone improved the performance with a factor 5-7. 
from:
var isNonAccessor = _hasOwn(desc, 'value');
to:
var isNonAccessor = Object.prototype.hasOwnProperty.call(input,prop);

My only guess of whats happening is that the optimizer fails due to the bind of _hasOwn for some reason. Any suggestions, or am I missing something in the behavior of the two lines here?

My test case is cloning a simple byte array of ~600 000 elements

**Comment by traviskaufman** [comment]
Thanks so much for looking into this! Sorry I took so long to respond. 

I've had other issues in the past with CycloneJS as a result of abusing function calls / constructors, so I'll definitely be looking into this as well. Would you happen to have a jsPerf or gist of your test case that I could work with?

**Comment by niklaskarla** [comment]
My turn to appoligize. I just ran a trivial case of copying an array with dummy objects: 

    var cloned = {'a':{'b':3},'c':{d:"asddsa"}}
    var o = [];
    for (var i = 0; i < 1e6; i++){
    //    o[i] = cloned;
        o[i] = i;
    }
     
    var s = new Date().getTime();
    CY.clone(o);
    var e = new Date().getTime();
    console.log("time taken: "+(e-s));

**Comment by traviskaufman** [comment]
I'm definitely seeing similar results as yourself (NodeJS v5.7.0 - OS X v10.11.4), almost a 30-50% increase in speed. 

Looks like the culprit here is the custom `_bind` implementation. Check out [inline-hasown.txt](https://github.com/traviskaufman/cycloneJS/files/264714/inline-hasown.txt) vs.  [no-inline-hasown.txt](https://github.com/traviskaufman/cycloneJS/files/264716/no-inline-hasown.txt). `malloc` calls were statistically significant in samples within `no-inline-hasown.txt`, while it doesn't even register when hasOwn wasn't inlined. I _want_ to say that the actual offending code is `boundArgs.concat(_slice.call(arguments))`, since that to me looks like it would cause new memory to be allocated. However I'm not familiar enough with how v8 optimizes code to be sure. 

Either way this is clearly an issue and I'll be submitting a PR with a fix for it. Thanks for looking into it!

**Comment by niklaskarla** [comment]
If you are interested I recall another issue I came across which is probably related to the reason for the disabled optimization, https://github.com/jashkenas/coffeescript/issues/3274. Anyway, thanks for fixing!
